version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./nextcloud.conf:/etc/nginx/conf.d/nextcloud.conf
    networks:
      - mynet
    restart: always
    depends_on:
      - nextcloud
      - onlyoffice

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_DB=solanteq
      - POSTGRES_USER=oc_solanteq_user
      - POSTGRES_PASSWORD=SomePass123@
    volumes:
      - pg_data:/var/lib/postgresql/data
      - /etc/postgresql/14/main/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - mynet
    restart: always

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=solanteq
      - POSTGRES_USER=oc_solanteq_user
      - POSTGRES_PASSWORD=SomePass123@
      - TRUSTED_PROXIES=nextcloud
      - OVERWRITECLIURL=https://nextcloud
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud
      - OVERWRITEHOST=nextcloud
      - REDIS_HOST=redis
    volumes:
      - nextcloud_data:/var/www/html
      - ./config.php:/var/www/html/config/config.php
    networks:
      - mynet
    restart: always
    depends_on:
      - postgresql
      - onlyoffice

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=xCMlaRYCsUvuTL8AB2KjDL8bvsnm5Ru0kz0JfC1VjVI=
    networks:
      - mynet
    restart: always
  
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - mynet
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - nginx

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    networks:
      - mynet
    ports:
      - "1025:1025"
      - "8025:8025"
    depends_on:
      - nginx

networks:
  mynet:

volumes:
  pg_data:
  nextcloud_data:
